apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-pv 
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /var/nfsshare/elk-data
    server: 10.254.186.52
  persistentVolumeReclaimPolicy: Recycle 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /var/nfsshare/elk-master
    server: 10.254.186.52
  persistentVolumeReclaimPolicy: Recycle
