apiVersion: v1
kind: PersistentVolume
metadata:
  name: ek-pv 
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /var/nfsshare/elk-data
    server: 10.254.186.52
  persistentVolumeReclaimPolicy: Recycle 
