kind: ConfigMap
apiVersion: v1
metadata:
  name: api-config-map
data:
  application.yml: |-
    elastic:
      url: http://10.254.186.59:9200
      kibana_url: http://10.254.186.59:5601
      prefix: vmanage

    custom:
      database:
        class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://10.254.186.52:1433;databaseName=vmanage;currentSchema=vis
        username: sa

    vmanage:
      bucket: attachment-storage
      s3-endpoint: http://10.254.186.59:9000/

    server:
      ssl:
        enabled: false