apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: docker-registry.default.svc:5000/vmanage/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
              name: http
              protocol: TCP
          env:
            - name: CUSTOM_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vmanage-secret
                  key: dbpassword
            - name: VMANAGE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: vmanage-secret
                  key: accessKeyId
            - name: VMANAGE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vmanage-secret
                  key: secretAccessKey
