kind: ConfigMap 
apiVersion: v1
metadata:
  name: api-config-map
data:
  application.yml: |-
    elastic:
      url: http://10.254.186.59:9200/test
      kibana_url: http://10.254.186.59:5601
      prefix: vmanage

    custom:
      database:
        class-name: org.postgresql.Driver
        url: jdbc:postgresql://10.254.186.59:5432/vmanage
        username: postgres
        password: Admin123!