apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: visiumpoc/frontendpoc:v0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: nginx-default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
      - name: nginx-default-conf
        configMap:
          name: nginx-config-map
          items:
            - key: default.conf
              path: default.conf