apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # use the shared ingress-nginx
    cert-manager.io/issuer: selfsigned-issuer
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: client-cluster-ip-service
          servicePort: 80
      - path: /api      
        backend:
          serviceName: api-cluster-ip-service
          servicePort: 8088
  tls:  
    - secretName: frontend-tls
status:
  loadBalancer:
    ingress:
    - {}