apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        #charset koi8-r;
        #access_log  /var/log/nginx/log/host.access.log  main;
    
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300; 

        location / {
            root   /usr/share/nginx/html;
            if (!-e $request_filename){
            rewrite ^(.*)$ /index.html break;
            }
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
